// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFAWcLdYMVki0kLVEkfwa46YAP5a0VxLk',
    appId: '1:621993083111:web:0fd040a015e95588c3e242',
    messagingSenderId: '621993083111',
    projectId: 'taskmaster2-0',
    authDomain: 'taskmaster2-0.firebaseapp.com',
    storageBucket: 'taskmaster2-0.firebasestorage.app',
    measurementId: 'G-28QFMS8Z0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ZTcblm9fDill2Bd58jsj8HhOr05wqRM',
    appId: '1:621993083111:android:84fab7ca742fdcb0c3e242',
    messagingSenderId: '621993083111',
    projectId: 'taskmaster2-0',
    storageBucket: 'taskmaster2-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjgYinP1jXVCvJS-P1YvXKxApH6EE1Xdk',
    appId: '1:621993083111:ios:cf145952aae19e0fc3e242',
    messagingSenderId: '621993083111',
    projectId: 'taskmaster2-0',
    storageBucket: 'taskmaster2-0.firebasestorage.app',
    iosBundleId: 'com.example.taskMaster20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjgYinP1jXVCvJS-P1YvXKxApH6EE1Xdk',
    appId: '1:621993083111:ios:cf145952aae19e0fc3e242',
    messagingSenderId: '621993083111',
    projectId: 'taskmaster2-0',
    storageBucket: 'taskmaster2-0.firebasestorage.app',
    iosBundleId: 'com.example.taskMaster20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFAWcLdYMVki0kLVEkfwa46YAP5a0VxLk',
    appId: '1:621993083111:web:9e60a1bc882c020fc3e242',
    messagingSenderId: '621993083111',
    projectId: 'taskmaster2-0',
    authDomain: 'taskmaster2-0.firebaseapp.com',
    storageBucket: 'taskmaster2-0.firebasestorage.app',
    measurementId: 'G-CFE9PNSKZD',
  );
}
